//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Arg.Terms
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("arg.terms.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atlas.
        /// </summary>
        public static string appName
        {
            get
            {
                return ResourceManager.GetString("appName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string btnAddClient
        {
            get
            {
                return ResourceManager.GetString("btnAddClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        public static string btnAddGroup
        {
            get
            {
                return ResourceManager.GetString("btnAddGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Region.
        /// </summary>
        public static string btnAddRegion
        {
            get
            {
                return ResourceManager.GetString("btnAddRegion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string btnClose
        {
            get
            {
                return ResourceManager.GetString("btnClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string btnSave
        {
            get
            {
                return ResourceManager.GetString("btnSave", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save and Close.
        /// </summary>
        public static string btnSaveAndClose
        {
            get
            {
                return ResourceManager.GetString("btnSaveAndClose", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string btnUpdate
        {
            get
            {
                return ResourceManager.GetString("btnUpdate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ** Select **.
        /// </summary>
        public static string ddlSelect
        {
            get
            {
                return ResourceManager.GetString("ddlSelect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Client.
        /// </summary>
        public static string hdrClientAdd
        {
            get
            {
                return ResourceManager.GetString("hdrClientAdd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Client.
        /// </summary>
        public static string hdrClientEdit
        {
            get
            {
                return ResourceManager.GetString("hdrClientEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Abbreviation.
        /// </summary>
        public static string lblAbbreviation
        {
            get
            {
                return ResourceManager.GetString("lblAbbreviation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string lblActions
        {
            get
            {
                return ResourceManager.GetString("lblActions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add Permission.
        /// </summary>
        public static string lblAddPermission
        {
            get
            {
                return ResourceManager.GetString("lblAddPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bill of Ladings.
        /// </summary>
        public static string lblBillofLadings
        {
            get
            {
                return ResourceManager.GetString("lblBillofLadings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BOL Number.
        /// </summary>
        public static string lblBOLNumber
        {
            get
            {
                return ResourceManager.GetString("lblBOLNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bookings.
        /// </summary>
        public static string lblBookings
        {
            get
            {
                return ResourceManager.GetString("lblBookings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string lblCity
        {
            get
            {
                return ResourceManager.GetString("lblCity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client .
        /// </summary>
        public static string lblClient
        {
            get
            {
                return ResourceManager.GetString("lblClient", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client Information.
        /// </summary>
        public static string lblClientInfo
        {
            get
            {
                return ResourceManager.GetString("lblClientInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string lblCode
        {
            get
            {
                return ResourceManager.GetString("lblCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact Name.
        /// </summary>
        public static string lblContact
        {
            get
            {
                return ResourceManager.GetString("lblContact", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string lblCustomer
        {
            get
            {
                return ResourceManager.GetString("lblCustomer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer Information.
        /// </summary>
        public static string lblCustomerInfo
        {
            get
            {
                return ResourceManager.GetString("lblCustomerInfo", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customers.
        /// </summary>
        public static string lblCustomers
        {
            get
            {
                return ResourceManager.GetString("lblCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date Complete.
        /// </summary>
        public static string lblDateComplete
        {
            get
            {
                return ResourceManager.GetString("lblDateComplete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Est. Start.
        /// </summary>
        public static string lblDateEstStart
        {
            get
            {
                return ResourceManager.GetString("lblDateEstStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date Started.
        /// </summary>
        public static string lblDateStarted
        {
            get
            {
                return ResourceManager.GetString("lblDateStarted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dflt Level.
        /// </summary>
        public static string lblDefaultPermission
        {
            get
            {
                return ResourceManager.GetString("lblDefaultPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string lblDescription
        {
            get
            {
                return ResourceManager.GetString("lblDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Destination.
        /// </summary>
        public static string lblDestination
        {
            get
            {
                return ResourceManager.GetString("lblDestination", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string lblEdit
        {
            get
            {
                return ResourceManager.GetString("lblEdit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        public static string lblEditGroup
        {
            get
            {
                return ResourceManager.GetString("lblEditGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit Permission.
        /// </summary>
        public static string lblEditPermission
        {
            get
            {
                return ResourceManager.GetString("lblEditPermission", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string lblGroupName
        {
            get
            {
                return ResourceManager.GetString("lblGroupName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client DB.
        /// </summary>
        public static string lblHasClientDB
        {
            get
            {
                return ResourceManager.GetString("lblHasClientDB", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string lblID
        {
            get
            {
                return ResourceManager.GetString("lblID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string lblIsActive
        {
            get
            {
                return ResourceManager.GetString("lblIsActive", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member.
        /// </summary>
        public static string lblIsMember
        {
            get
            {
                return ResourceManager.GetString("lblIsMember", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member Name.
        /// </summary>
        public static string lblMemberName
        {
            get
            {
                return ResourceManager.GetString("lblMemberName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Members.
        /// </summary>
        public static string lblMembers
        {
            get
            {
                return ResourceManager.GetString("lblMembers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string lblNotes
        {
            get
            {
                return ResourceManager.GetString("lblNotes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Object Name.
        /// </summary>
        public static string lblObjectName
        {
            get
            {
                return ResourceManager.GetString("lblObjectName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Origin.
        /// </summary>
        public static string lblOrigin
        {
            get
            {
                return ResourceManager.GetString("lblOrigin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string lblPermissionLevel
        {
            get
            {
                return ResourceManager.GetString("lblPermissionLevel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string lblPriority
        {
            get
            {
                return ResourceManager.GetString("lblPriority", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string lblRecords
        {
            get
            {
                return ResourceManager.GetString("lblRecords", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Region Name.
        /// </summary>
        public static string lblRegionName
        {
            get
            {
                return ResourceManager.GetString("lblRegionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string lblRemove
        {
            get
            {
                return ResourceManager.GetString("lblRemove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string lblSource
        {
            get
            {
                return ResourceManager.GetString("lblSource", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string lblStatus
        {
            get
            {
                return ResourceManager.GetString("lblStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Task Name.
        /// </summary>
        public static string lblTaskName
        {
            get
            {
                return ResourceManager.GetString("lblTaskName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to View List.
        /// </summary>
        public static string lblViewList
        {
            get
            {
                return ResourceManager.GetString("lblViewList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string mnuAbout
        {
            get
            {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string mnuClients
        {
            get
            {
                return ResourceManager.GetString("mnuClients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string mnuContactForm
        {
            get
            {
                return ResourceManager.GetString("mnuContactForm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string mnuDashboard
        {
            get
            {
                return ResourceManager.GetString("mnuDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string mnuHome
        {
            get
            {
                return ResourceManager.GetString("mnuHome", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to multiple updates.
        /// </summary>
        public static string msgActionMultipleUpdates
        {
            get
            {
                return ResourceManager.GetString("msgActionMultipleUpdates", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add record failed.
        /// </summary>
        public static string msgAddFail
        {
            get
            {
                return ResourceManager.GetString("msgAddFail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record successfully added.
        /// </summary>
        public static string msgAddSuccess
        {
            get
            {
                return ResourceManager.GetString("msgAddSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Multiple records updated; list being refreshed.
        /// </summary>
        public static string msgMultipleUpdatesSuccess
        {
            get
            {
                return ResourceManager.GetString("msgMultipleUpdatesSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        public static string msgRequiredFieldsError
        {
            get
            {
                return ResourceManager.GetString("msgRequiredFieldsError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Record successfully updated.
        /// </summary>
        public static string msgUpdateSuccess
        {
            get
            {
                return ResourceManager.GetString("msgUpdateSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Atlas.
        /// </summary>
        public static string pgAppName
        {
            get
            {
                return ResourceManager.GetString("pgAppName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Client List.
        /// </summary>
        public static string pgClientList
        {
            get
            {
                return ResourceManager.GetString("pgClientList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string pgDashboard
        {
            get
            {
                return ResourceManager.GetString("pgDashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Bill of Ladings.
        /// </summary>
        public static string pgTitleBillofLadings
        {
            get
            {
                return ResourceManager.GetString("pgTitleBillofLadings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Customer Summary.
        /// </summary>
        public static string pgTitleCustomerSummary
        {
            get
            {
                return ResourceManager.GetString("pgTitleCustomerSummary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Clients.
        /// </summary>
        public static string pgTitleManageClients
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageClients", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Customers.
        /// </summary>
        public static string pgTitleManageCustomers
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageCustomers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Group Members.
        /// </summary>
        public static string pgTitleManageGroupMembers
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageGroupMembers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Groups.
        /// </summary>
        public static string pgTitleManageGroups
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageGroups", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Group Members.
        /// </summary>
        public static string pgTitleManageMembers
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageMembers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Memberships.
        /// </summary>
        public static string pgTitleManageMemberships
        {
            get
            {
                return ResourceManager.GetString("pgTitleManageMemberships", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Permissions.
        /// </summary>
        public static string pgTitleManagePermissions
        {
            get
            {
                return ResourceManager.GetString("pgTitleManagePermissions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manage Regions.
        /// </summary>
        public static string pgTitleRegions
        {
            get
            {
                return ResourceManager.GetString("pgTitleRegions", resourceCulture);
            }
        }
    }
}
